<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <WarningLevel>4</WarningLevel>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Humanizer" />
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
    <PackageReference Include="NLog.Extensions.Logging" />
    <PackageReference Include="System.Data.DataSetExtensions" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" />
    <PackageReference Include="YoutubeExplode.Converter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StreamShorts.Library\StreamShorts.Library.csproj" />
    <ProjectReference Include="..\StreamShortsMVVM\StreamShortsMVVM.csproj" />
  </ItemGroup>
</Project>