<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Humanizer" />
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="System.Data.DataSetExtensions" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" />
    <PackageReference Include="YoutubeExplode.Converter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StreamShorts.Library\StreamShorts.Library.csproj" />
  </ItemGroup>
</Project>
